# SPDX-License-Identifier: CC-BY-SA-4.0

"""Repository port for persisted ACL entries."""

from __future__ import annotations

from collections.abc import Sequence
from typing import Protocol

from acl.domain import ACLEntry, ACLEntryId, ResourceRef, SubjectRef


class ACLEntryRepository(Protocol):
    def entries_for(self, resource: ResourceRef, operation: str) -> list[ACLEntry]: ...
    def list_by_operation(self, operation: str, resource_type: str) -> list[ACLEntry]: ...
    def list_by_resource(self, resource: ResourceRef) -> list[ACLEntry]: ...
    def get(self, entry_id: ACLEntryId) -> ACLEntry | None: ...
    def save(self, entry: ACLEntry) -> None: ...
    def delete(self, entry_id: ACLEntryId) -> None: ...
    def replace_entries(self, resource: ResourceRef, entries: Sequence[ACLEntry]) -> None: ...
    def delete_by_resource(self, resource: ResourceRef) -> None: ...
    def delete_by_subject(self, subject: SubjectRef) -> None: ...
    def is_empty(self) -> bool: ...
