# SPDX-License-Identifier: CC-BY-SA-4.0
"""Persistence ports for Auth core and optional extensions."""

from __future__ import annotations

from datetime import datetime, timedelta
from typing import Protocol

from auth.domain.account import Account
from auth.domain.access_control import ResourceRef, SubjectRef
from auth.domain.credentials import LocalCredential
from auth.domain.identity import ExternalIdentity
from auth.domain.profile import AuthorizationProfile, Group
from auth.domain.session import AuthSession
from auth.domain.token import RefreshTokenRecord
from auth.domain.types import (
    AccountId,
    ExternalIdentityId,
    GroupId,
    ProfileId,
    RefreshTokenId,
    SessionId,
    TokenFamilyId,
)


class AccountRepository(Protocol):
    def get_by_id(self, account_id: AccountId) -> Account | None: ...

    def get_by_username(self, username: str) -> Account | None: ...

    def get_by_email(self, email: str) -> Account | None: ...

    def exists_active(self) -> bool: ...


class AccountManagementRepository(AccountRepository, Protocol):
    def save(self, account: Account) -> None: ...

    def delete(self, account_id: AccountId) -> None: ...

    def list(self) -> list[Account]: ...

    def count(self) -> int: ...

    def next_id(self) -> AccountId: ...


class CredentialRepository(Protocol):
    def get(self, account_id: AccountId) -> LocalCredential | None: ...

    def save(self, credential: LocalCredential) -> None: ...

    def delete(self, account_id: AccountId) -> None: ...

    def record_failure(
        self,
        account_id: AccountId,
        *,
        now: datetime,
        max_attempts: int,
        lockout_duration: timedelta,
    ) -> LocalCredential | None: ...

    def reset_failures(self, account_id: AccountId) -> LocalCredential | None: ...


class ExternalIdentityRepository(Protocol):
    def get_by_provider_issuer_subject(self, provider: str, issuer: str, subject: str) -> ExternalIdentity | None: ...

    def list_for_account(self, account_id: AccountId) -> list[ExternalIdentity]: ...

    def save(self, identity: ExternalIdentity) -> None: ...

    def delete(self, identity_id: ExternalIdentityId) -> None: ...


class ProfileRepository(Protocol):
    def get(self, profile_id: ProfileId) -> AuthorizationProfile | None: ...

    def save(self, profile: AuthorizationProfile) -> None: ...

    def assign_groups(self, profile_id: ProfileId, groups: frozenset[str]) -> AuthorizationProfile | None: ...

    def increment_version(self, profile_id: ProfileId) -> AuthorizationProfile | None: ...


class GroupRepository(Protocol):
    def get(self, group_id: GroupId) -> Group | None: ...

    def list(self) -> list[Group]: ...

    def save(self, group: Group) -> None: ...

    def delete(self, group_id: GroupId) -> None: ...


class GroupMembershipRepository(Protocol):
    def groups_for_account(self, account_id: AccountId) -> frozenset[str]: ...

    def add(self, account_id: AccountId, group: str) -> None: ...

    def remove(self, account_id: AccountId, group: str) -> None: ...

    def remove_all(self, account_id: AccountId) -> None: ...


class SessionRepository(Protocol):
    def create(self, session: AuthSession) -> None: ...

    def get(self, session_id: SessionId) -> AuthSession | None: ...

    def save(self, session: AuthSession) -> None: ...

    def delete(self, session_id: SessionId) -> None: ...

    def delete_for_account(self, account_id: AccountId) -> None: ...


class TokenRepository(Protocol):
    def save_refresh_token(self, record: RefreshTokenRecord) -> None: ...

    def get_refresh_token_by_hash(self, token_hash: str) -> RefreshTokenRecord | None: ...

    def get_refresh_token(self, token_id: RefreshTokenId) -> RefreshTokenRecord | None: ...

    def list_refresh_family(self, family_id: TokenFamilyId) -> list[RefreshTokenRecord]: ...

    def save_refresh_family(self, records: list[RefreshTokenRecord]) -> None: ...


class TokenRevocationStore(Protocol):
    def revoke(self, jti: str, ttl_seconds: int) -> None: ...

    def is_revoked(self, jti: str) -> bool: ...


class AclEntryRepository(Protocol):
    def entries_for(self, resource: ResourceRef) -> list[object]: ...

    def list_by_operation(self, operation: str) -> list[object]: ...

    def save(self, entry: object) -> None: ...

    def delete(self, entry_id: str) -> None: ...

    def delete_by_resource(self, resource: ResourceRef) -> None: ...

    def delete_by_subject(self, subject: SubjectRef) -> None: ...


class MacPolicyRepository(Protocol):
    def policy_for(self, resource: ResourceRef) -> object | None: ...

    def save_policy(self, policy: object) -> None: ...

    def delete_policy(self, policy_id: str) -> None: ...


class DacGrantRepository(Protocol):
    def grants_for(self, resource: ResourceRef) -> list[object]: ...

    def save_grant(self, grant: object) -> None: ...

    def delete_grant(self, grant_id: str) -> None: ...

    def controls_for(self, resource: ResourceRef) -> object | None: ...

    def set_control(self, control: object) -> None: ...
